[package]
name = "app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.rest]
path = "../rest"

[dependencies.dao_impl]
path = "../dao_impl"

[dependencies.dao]
path = "../dao"

[dependencies.service_impl]
path = "../service_impl"

[dependencies.tokio]
version = "1.37.0"
features = ["full"]

[dependencies.sqlx]
version = "0.7.4"
features = ["runtime-tokio", "sqlite"]
