name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: "true"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Formatting
      run: cargo fmt --all -- --check
    - name: Build local version
      run: cargo build --verbose
    - name: Build OIDC version
      run: cargo build --verbose --no-default-features --features oidc
    - name: Run tests
      run: cargo test --verbose
